# Generated by Django 3.2.5 on 2021-07-17 21:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coordinate',
            old_name='latitute',
            new_name='latitude',
        ),
    ]
