# Generated by Django 3.2.5 on 2021-07-18 00:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0002_rename_latitute_coordinate_latitude'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rating',
            old_name='level',
            new_name='rating',
        ),
    ]
